package pharoslabut.logger;

/**
 * Logs messages generated by the Pharos Middleware.
 * 
 * @author Chien-Liang Fok
 */
public class Logger {

	private static String getPrefix() {
		// Add the name of the calling method to the beginning of the message.
		StackTraceElement[] stackTraceElements = Thread.currentThread().getStackTrace();
		StackTraceElement caller = stackTraceElements[3];
		String callingClassName = caller.getClassName();
		String callingMethodName = caller.getMethodName();
		
		String result = callingClassName + ": " + callingMethodName + ": ";
		return result;
	}
	
	/**
	 * Logs a message to StdErr.
	 * The caller's class and method name is added to the front of the message.
	 * 
	 * @param msg The message to log.
	 */
	public static void logErr(String msg) {
		String result = getPrefix() + "ERROR: " + msg;
		System.err.println(result);
	}
	
	/**
	 * Logs a message to StdErr and a file logger.
	 * The caller's class and method name is added to the front of the message.
	 * 
	 * @param msg The message to log.
	 */
	public static void logErr(String msg, FileLogger flogger) {
		String result = getPrefix() + "ERROR: " + msg;
		System.err.println(result);
		flogger.log(result);
	}
	
	/**
	 * Logs a message to StdOut.
	 * The caller's class and method name is added to the front of the message.
	 * 
	 * @param msg The message to log.
	 */
	public static void log(String msg) {
		String result = getPrefix() + msg;
		System.out.println(result);
	}
	
	/**
	 * Logs a message to StdOut and a file logger.
	 * The caller's class and method name is added to the front of the message.
	 * 
	 * @param msg The message to log.
	 */
	public static void log(String msg, FileLogger flogger) {
		String result = getPrefix() + msg;
		System.out.println(result);
		flogger.log(result);
	}
	
	/**
	 * Logs a message to StdOut if debug mode is enabled.
	 * Debug mode is enabled by the system property "PharosMiddleware.debug" being set
	 * to a value that is not null.
	 * The caller's class and method name is added to the front of the message.
	 * 
	 * @param msg The message to log.
	 */
	public static void logDbg(String msg) {
		if (System.getProperty ("PharosMiddleware.debug") != null) {
			String result = getPrefix() + msg;
			System.out.println(result);
		}
	}
	
	/**
	 * Logs a message to StdOut and a file logger if debug mode is enabled.
	 * Debug mode is enabled by the system property "PharosMiddleware.debug" being set
	 * to a value that is not null.
	 * The caller's class and method name is added to the front of the message.
	 * 
	 * @param msg The message to log.
	 */
	public static void logDbg(String msg, FileLogger flogger) {
		if (System.getProperty ("PharosMiddleware.debug") != null) {
			String result = getPrefix() + msg;
			System.out.println(result);
			flogger.log(result);
		}
	}
}
