# This script takes as input the name of the log file generated by the Player Server.
# It searches for the MCU_STATUS messages that are periodically sent from the MCU,
# extracts the relevant information, and prints it to the screen in a tab-separated
# table format.
#
# Here is an example of the log statements this script searches for:
# [1297085536876] PharosServer: MCU Message: MCU_STATUS: tach speed = -1, target speed = 0, motor power = 62, steering angle = 0.000000
#
# To use this script, execute:
#  $ perl parseLogMCUStatus.pl <name of log file>
#
# Usually, you will want to redirect its output into a file.  To do this, execute:
#  $ perl parseLogMCUStatus.pl <name of log file> | tee MCUStatusTable.txt
#
# The above command will save the table into the file called "MCUStatusTable.txt"
# You can then import this file into Excel or Matlab to perform further processing.
#
# Author: Chien-Liang Fok
# Created: 02/08/2011
#

$numArgs = $#ARGV + 1;
if ($numArgs != 1) {
	print "Usage: perl parseLogMCUStatus.pl [log file name]\n";
	exit 0;
}

$LOGFILE = $ARGV[0];
open(LOGFILE) or die("Could not open log file.");

# Print the table header...
print "Time Stamp (ms)\tDelta Time (ms)\tDelta Time (s)\tTach Speed\tTarget Speed\tMotor Power\tSteering Angle\n";

while (my $line  = <LOGFILE>) {
	
	if ($line =~ m/Starting experiment at time/) {
		@array = split(/(\s+|:)/, $line);
		$startTime = $array[16];
	}
	elsif($line =~ m/MCU Message: MCU_STATUS:/) {
		@array = split(/(\[|\]|\s+|,)/, $line);
		$timeStamp = $array[2];
		$deltaTime = $timeStamp - $startTime;
		$deltaTimeS = $deltaTime / 1000;
		
		$tachSpeed = $array[20];
		$targetSpeed = $array[30];
		$motorPower = $array[40];
		$steeringAngle = $array[50];
		
#		print "Array:\n";
#		$indx = 0;
#		foreach (@array) {
#			print "$indx: $_\n";
#			$indx++;
#		}
		
		print "$timeStamp\t$deltaTime\t$deltaTimeS\t$tachSpeed\t$targetSpeed\t$motorPower\t$steeringAngle\n";
    } 
}

