package pharoslabut.navigate;

import java.io.*;
//import java.util.*;

/**
 * Reads in a GPS trace file generated by Tony's program.
 * The file is in plain text where each line consists of:
 * [longitude] [latitude] [speed] [pause time at destination in seconds]
 * 
 * @author Chien-Liang Fok
 */
public class GPSTraceReader {

	public static GPSMotionScript readTraceFile(String fileName) {
		GPSMotionScript result = new GPSMotionScript();
		try {
			BufferedReader input =  new BufferedReader(new FileReader(fileName));
			try {
				String line = null;
				int lineno = 1;
				while (( line = input.readLine()) != null) {
					if (!line.equals("")) {
						//StringTokenizer st = new StringTokenizer(line);
						try {
							String[] elem = line.split("[\\s]+");
//							System.out.println("Read in line: " + line);
//							for (int i=0; i < elem.length; i++) {
//								System.out.println(i + ": " + elem[i]);
//							}
							double longitude = Double.valueOf(elem[0]);
							double latitude = Double.valueOf(elem[1]);
							double speed = Double.valueOf(elem[2]);
							long pauseTime = Long.valueOf(elem[3]);
							Location loc = new Location(latitude, longitude);
							result.addWayPoint(loc, pauseTime, speed);
						} catch(Exception e) {
							e.printStackTrace();
							System.err.println("Warning: Ignoring line " + lineno + " of motion script " + fileName);
						}
					}
					lineno++;
				}
			}
			finally {
				input.close();
			}
		}
		catch (IOException ex){
			ex.printStackTrace();
		}
		return result;
	}
	
	public static void main(String[] args) {
		//GPSMotionScript script = GPSTraceReader.readTraceFile("M11/M11-MotionScripts/m11-gps-lollipop-0.6-4spause.txt");
		//GPSMotionScript script = GPSTraceReader.readTraceFile("bin/LBJ-MotionScript-1.txt");
		GPSMotionScript script = GPSTraceReader.readTraceFile("MM7/LBJ-Lot-BackAndForth-1.5.txt");
		System.out.println("Read in the following GPSMotionScript:\n" + script);
	}
}
