package pharoslabut;


import playerclient.NoNewDataException;
import playerclient.Position2DListener;
import playerclient.structures.position2d.PlayerPosition2dData;
import java.awt.*;
import javax.imageio.ImageReader;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pharoslabut.RobotMover;
import playerclient.structures.PlayerPoint2d;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.Scanner;

import javax.swing.Timer;

import javax.imageio.ImageIO;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Mar 6, 2011, 10:19:07 PM
 */
/**
 *
 * @author Tad M
 */
public class NewJFrame extends javax.swing.JFrame implements Position2DListener, ActionListener  {
    /** Creates new form NewJFrame */
    private static RobotMover XueHua, XueHuaPos;
    protected  double XueHuaXf = 0, XueHuaYf = 0, XueHuaYaw =0;
    protected int Quarter = 1000, Half =2000, T_Quarter = 3000, Full = 4000;
    protected static int delay = 1000;
    
    protected String Time;
    BufferedImage image ;
    public String mapfile;
    public int src_x, src_y, dest_x, dest_y;
    private final static String newline = "\n";
    static StopWatch s = new StopWatch();
  protected static int count= 0;
    
    public NewJFrame() {
        initComponents();
      XueHua =  new RobotMover("10.11.12.32", 6665, "log.txt",  false);
      XueHuaPos = new RobotMover("10.11.12.32", 6666, "log.txt", false);
      ActionListener taskPerformer = new ActionListener() {
          public void actionPerformed(ActionEvent evt) {
          	  XueHuaPos.INS_UpdateX();
                XueHuaPos.INS_UpdateY();
                
                String XueHuaX = Double.toString(XueHuaPos.Xpos);
                String XueHuaY = Double.toString(XueHuaPos.Ypos);
                
                jTextField1.setText(XueHuaX); 
                jTextField2.setText(XueHuaY);
                
          }
      };
      Timer insT = new Timer(delay, taskPerformer);
      insT.start();
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Xpos");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("Ypos");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("Orientation");

        jTextField4.setText("Mode");

        jTextField5.setText("Time");

        jButton1.setText("NW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("N");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("NE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Relative Xpos");

        jLabel2.setText("Relative Ypos");

        jLabel3.setText("Relative Orientation");

        jLabel4.setText("Mode");

        jLabel5.setText("Time Elapsed");

        jTextField6.setText("Blocked/Open");

        jLabel6.setText("Status");

        jButton10.setText("Pathfinding");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton10ActionPerformed(evt);
				} catch (NoNewDataException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jButton4.setText("W");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Stop");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("E");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("SW");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("S");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("SE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jButton10)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton9))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    public void UpdateInfo()
    {
        XueHuaPos.INS_UpdateX();
        XueHuaPos.INS_UpdateY();
        XueHuaPos.INS_UpdateOrient();
        
        String XueHuaX = Double.toString(XueHuaPos.Xpos+XueHuaPos.BaseX);
        String XueHuaY = Double.toString(XueHuaPos.Ypos+XueHuaPos.BaseY);
        String XueHuaYaw = Double.toString(XueHuaPos.Yaw+XueHuaPos.BaseYaw);
        jTextField1.setText(XueHuaX); 
        jTextField2.setText(XueHuaY);
        jTextField3.setText(XueHuaYaw);
        
        double XueHuaTime = s.getElapsedTimeSecs();
        Time = Double.toString(XueHuaTime);
        jTextField5.setText(Time);
    } 
     
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    		

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        //turn 45 degrees CCW move
    	System.out.println("Debug Msg: Turn NW");
    	XueHua.movW(Quarter);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		{	 
             XueHua.moveForward(); 
            
             XueHuaPos.INS_UpdateX();
             XueHuaPos.INS_UpdateY();
             
             String XueHuaX = Double.toString(XueHuaPos.Xpos);
             String XueHuaY = Double.toString(XueHuaPos.Ypos);
             
             jTextField1.setText(XueHuaX); 
             jTextField2.setText(XueHuaY);
             
           double XueHuaTime = s.getElapsedTimeSecs();
             Time = Double.toString(XueHuaTime);
             jTextField5.setText(Time);
             
                                  }

		}// TODO add your handling code here:
//GEN-LAST:event_jButton2ActionPerformed

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        // Turn NW
 	   System.out.println("Debug Msg: Move NE");
 	   XueHua.movW(Quarter);
    }          
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    			System.out.println("Debug Msg: Turn West");
    			XueHua.movW(Half);
    			jTextField4.setText("30");
    }//GEN-LAST:event_jButton4ActionPerformed

  

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    				 jTextField4.setText("Manual");
                     XueHua.stop();// Add code here 
                     // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
 
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
		System.out.println("Debug Msg: Turn East");
		XueHua.movE(Half);
    }//GEN-LAST:event_jButton6ActionPerformed
                            

   private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
	   System.out.println("Debug Msg: Move SW");
	   XueHua.movW(T_Quarter);
	   //turn 225 degrees CCW and move straight
   }                                        

   private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 		System.out.println("Debug Msg: Move Backwards");
            XueHua.movE(Full);
}//GEN-LAST:event_jButton8ActionPerformed
   private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
	  System.out.println("Debug Msg: Move SE");
      XueHua.movE(T_Quarter);
   }               // turn 315 degrees CCW and move 
    /**
    * @param args the command line arguments
    */
   
   private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) throws NoNewDataException, IOException {//GEN-FIRST:event_jButton10ActionPerformed
       	jTextField4.setText("Pathfinding Mode");
	    JFrame Oldinputs = new JFrame();
        String inputs = JOptionPane.showInputDialog(Oldinputs, "Previous File name is "+mapfile);
	    JFrame File = new JFrame();
	    String mapfile = JOptionPane.showInputDialog(File, "Input Map File name");

	    System.out.println(mapfile);
	    
	 /*   ImageIcon Display = new ImageIcon(mapfile);
	    jButton11.setIcon(Display);		
					// display map 8 */
	    JFrame frame = new JFrame();
	    String result = JOptionPane.showInputDialog(frame, "Input Initial Coordinates X  Y separate with space");
		Scanner Scan = new Scanner(result);
		
		// Stop movement
		XueHua.stop();
		if(result.equals("/n")){
			src_x = src_x+0;
			src_y = src_y+0;
		}
		else{
		src_x = Scan.nextInt();
		XueHua.BaseX = src_x;
		src_y = Scan.nextInt();
		XueHua.BaseY = src_y;
	    //TODO: call RobotMover.ManUpdateINS(x,y,yaw)
	    System.out.println(result);
		}
	    
	    JFrame Dest = new JFrame();
	    String Desresult = JOptionPane.showInputDialog(Dest, "Destination Coordinates in X Y separate with space");
	    Scan = new Scanner(Desresult);
	    if(Desresult.equals("/n"))
	    {
	    	dest_x = dest_x+0;
	    	dest_y = dest_y+0;
	    }
	    else{
	    dest_x =Scan.nextInt();
	    dest_y =Scan.nextInt();
	    }
	    System.out.println(Desresult);
	    
	    File ascii_map = new File(mapfile);	
		Mapping map  = new Mapping();
		map.parse(ascii_map);
		map.createBuffer();
		map.printBuffer(this);
		//map.printMap();
		
		PathFind pf  = new PathFind(map,1);
		pf.A_path(src_x, src_y, dest_x, dest_y, 0);
		pf.result.printPath();
		pf.result.printMov();
		map.printBuffer(this);
	    //TODO: call PathFind.A_path
	    
	    
	    //TODO: Handle movement list
	    
	    int i;
	    for (i=0; i<pf.result.MovSize(); i++)
	    {
	    	System.out.println("Debug Msg: Execute cmd "+ i);
	    	XueHua.FB_Mov(pf.result.GetMov(i),this);
	    }
	    
	    XueHua.stop();
	    // while new command 
	    //move
	    // update
	    // check for new command
             
	    	//  XueHuaPos.INS_UpdateX();
            //  XueHuaPos.INS_UpdateY();


     //         private void jTextField7ActionPerformed(java.awt.event.ActionEvent ) {
                  // TODO add your handling code here:
         //     }     

// TODO add your handling code here: this is a temp button for manual updates from INS for nowT
    }//GEN-LAST:event_jButton10ActionPerformed
   
   
   public void UpdateMap(String s)
   {
	   
	   jTextArea1.append(s);
	   
   }
   
   public void ReplaceMapLine(String s, int row, int width)
   {
	   jTextArea1.replaceRange(s, row*width, row*(width+1));
   }
   
   // Note that all degree movements are relative to the current heading of the robot, not absolute heading.
    public static void main(String args[]) {
    	
    	s.start();
  
    	
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
            public void run() {
                new NewJFrame().setVisible(true);
               
  //            s.start(delay, taskPerformer); 

                //code you want to time goes here
              
                
            }
  // Add Automatic Control Components here
        });
        
    }

    private static void addPos2DListener(RobotMover xueHuaPos2) {
		// TODO Auto-generated method stub
		
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private  javax.swing.JTextField jTextField1;
    private  javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel Map;
    private javax.swing.JButton jButton11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    

    // End of variables declaration//GEN-END:variables
	@Override
	public void newPlayerPosition2dData(PlayerPosition2dData data) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		
	}

}
