/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RadioSignalResultsMsg'
 * message type.
 */

public class RadioSignalResultsMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 14;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 2;

    /** Create a new RadioSignalResultsMsg of size 14. */
    public RadioSignalResultsMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RadioSignalResultsMsg of the given data_length. */
    public RadioSignalResultsMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioSignalResultsMsg with the given data_length
     * and base offset.
     */
    public RadioSignalResultsMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioSignalResultsMsg using the given byte array
     * as backing store.
     */
    public RadioSignalResultsMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioSignalResultsMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RadioSignalResultsMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioSignalResultsMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RadioSignalResultsMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioSignalResultsMsg embedded in the given message
     * at the given base offset.
     */
    public RadioSignalResultsMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioSignalResultsMsg embedded in the given message
     * at the given base offset and length.
     */
    public RadioSignalResultsMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RadioSignalResultsMsg> \n";
      try {
        s += "  [idReceiver=0x"+Long.toHexString(get_idReceiver())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [idSender=0x"+Long.toHexString(get_idSender())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [seqno=0x"+Long.toHexString(get_seqno())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rssi=0x"+Long.toHexString(get_rssi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [lqi=0x"+Long.toHexString(get_lqi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [timestamp=0x"+Long.toHexString(get_timestamp())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: idReceiver
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'idReceiver' is signed (false).
     */
    public static boolean isSigned_idReceiver() {
        return false;
    }

    /**
     * Return whether the field 'idReceiver' is an array (false).
     */
    public static boolean isArray_idReceiver() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'idReceiver'
     */
    public static int offset_idReceiver() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'idReceiver'
     */
    public static int offsetBits_idReceiver() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'idReceiver'
     */
    public int get_idReceiver() {
        return (int)getUIntBEElement(offsetBits_idReceiver(), 16);
    }

    /**
     * Set the value of the field 'idReceiver'
     */
    public void set_idReceiver(int value) {
        setUIntBEElement(offsetBits_idReceiver(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'idReceiver'
     */
    public static int size_idReceiver() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'idReceiver'
     */
    public static int sizeBits_idReceiver() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: idSender
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'idSender' is signed (false).
     */
    public static boolean isSigned_idSender() {
        return false;
    }

    /**
     * Return whether the field 'idSender' is an array (false).
     */
    public static boolean isArray_idSender() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'idSender'
     */
    public static int offset_idSender() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'idSender'
     */
    public static int offsetBits_idSender() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'idSender'
     */
    public int get_idSender() {
        return (int)getUIntBEElement(offsetBits_idSender(), 16);
    }

    /**
     * Set the value of the field 'idSender'
     */
    public void set_idSender(int value) {
        setUIntBEElement(offsetBits_idSender(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'idSender'
     */
    public static int size_idSender() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'idSender'
     */
    public static int sizeBits_idSender() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: seqno
    //   Field type: long, unsigned
    //   Offset (bits): 32
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'seqno' is signed (false).
     */
    public static boolean isSigned_seqno() {
        return false;
    }

    /**
     * Return whether the field 'seqno' is an array (false).
     */
    public static boolean isArray_seqno() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'seqno'
     */
    public static int offset_seqno() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'seqno'
     */
    public static int offsetBits_seqno() {
        return 32;
    }

    /**
     * Return the value (as a long) of the field 'seqno'
     */
    public long get_seqno() {
        return (long)getUIntBEElement(offsetBits_seqno(), 32);
    }

    /**
     * Set the value of the field 'seqno'
     */
    public void set_seqno(long value) {
        setUIntBEElement(offsetBits_seqno(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'seqno'
     */
    public static int size_seqno() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'seqno'
     */
    public static int sizeBits_seqno() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssi
    //   Field type: short, unsigned
    //   Offset (bits): 64
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssi' is signed (false).
     */
    public static boolean isSigned_rssi() {
        return false;
    }

    /**
     * Return whether the field 'rssi' is an array (false).
     */
    public static boolean isArray_rssi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rssi'
     */
    public static int offset_rssi() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssi'
     */
    public static int offsetBits_rssi() {
        return 64;
    }

    /**
     * Return the value (as a short) of the field 'rssi'
     */
    public short get_rssi() {
        return (short)getUIntBEElement(offsetBits_rssi(), 8);
    }

    /**
     * Set the value of the field 'rssi'
     */
    public void set_rssi(short value) {
        setUIntBEElement(offsetBits_rssi(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'rssi'
     */
    public static int size_rssi() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rssi'
     */
    public static int sizeBits_rssi() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: lqi
    //   Field type: short, unsigned
    //   Offset (bits): 72
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'lqi' is signed (false).
     */
    public static boolean isSigned_lqi() {
        return false;
    }

    /**
     * Return whether the field 'lqi' is an array (false).
     */
    public static boolean isArray_lqi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'lqi'
     */
    public static int offset_lqi() {
        return (72 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'lqi'
     */
    public static int offsetBits_lqi() {
        return 72;
    }

    /**
     * Return the value (as a short) of the field 'lqi'
     */
    public short get_lqi() {
        return (short)getUIntBEElement(offsetBits_lqi(), 8);
    }

    /**
     * Set the value of the field 'lqi'
     */
    public void set_lqi(short value) {
        setUIntBEElement(offsetBits_lqi(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'lqi'
     */
    public static int size_lqi() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'lqi'
     */
    public static int sizeBits_lqi() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: timestamp
    //   Field type: long, unsigned
    //   Offset (bits): 80
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'timestamp' is signed (false).
     */
    public static boolean isSigned_timestamp() {
        return false;
    }

    /**
     * Return whether the field 'timestamp' is an array (false).
     */
    public static boolean isArray_timestamp() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'timestamp'
     */
    public static int offset_timestamp() {
        return (80 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'timestamp'
     */
    public static int offsetBits_timestamp() {
        return 80;
    }

    /**
     * Return the value (as a long) of the field 'timestamp'
     */
    public long get_timestamp() {
        return (long)getUIntBEElement(offsetBits_timestamp(), 32);
    }

    /**
     * Set the value of the field 'timestamp'
     */
    public void set_timestamp(long value) {
        setUIntBEElement(offsetBits_timestamp(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'timestamp'
     */
    public static int size_timestamp() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'timestamp'
     */
    public static int sizeBits_timestamp() {
        return 32;
    }

}
