/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartGUI.java
 *
 * Created on Apr 21, 2011, 10:44:06 PM
 */
package pharoslabut.cartographer;

import java.io.IOException;


/**
 *
 * @author Kevin
 */
public class StartGUI extends javax.swing.JFrame {

	static String [] mainArgs = null;
	static PathPlannerThread ppt = null;
	static boolean started = false;
	
    /** Creates new form StartGUI */
    public StartGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        TimeLimitTextField = new javax.swing.JTextField();
        TimeLimitLabel = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();
        StatusLabel = new javax.swing.JLabel();
        StartingPositionComboBox = new javax.swing.JComboBox();
        StartingPositionLabel = new javax.swing.JLabel();
        StopMotion = new javax.swing.JButton();
        EmergencyStopButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cartogtrapher GUI");

        TimeLimitTextField.setText("180");
        TimeLimitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeLimitTextFieldActionPerformed(evt);
            }
        });

        TimeLimitLabel.setText("Execution Time Limit (seconds):");

        StartButton.setText("Start!");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        StatusLabel.setText("Waiting to start mapping routine ...");

        StartingPositionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bottom Left Corner, Facing North (pi/2)", "Bottom Right Corner, Facing West (pi)", "Upper Left Corner, Facing East (0)", "Upper Right Corner, Facing South (-pi/2)" }));
        StartingPositionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartingPositionComboBoxActionPerformed(evt);
            }
        });

        StartingPositionLabel.setText("Starting Position");

        StopMotion.setText("Stop Motion");
        StopMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopMotionActionPerformed(evt);
            }
        });

        EmergencyStopButton.setText("Emergency Stop!");
        EmergencyStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyStopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TimeLimitLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TimeLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StartingPositionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(StartingPositionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StartButton)
                        .addGap(18, 18, 18)
                        .addComponent(StopMotion)
                        .addGap(18, 18, 18)
                        .addComponent(EmergencyStopButton))
                    .addComponent(StatusLabel))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeLimitLabel)
                    .addComponent(TimeLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartingPositionLabel)
                    .addComponent(StartingPositionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartButton)
                    .addComponent(StopMotion)
                    .addComponent(EmergencyStopButton))
                .addGap(30, 30, 30)
                .addComponent(StatusLabel)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void TimeLimitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // this doesn't need to do anything
    }                                                  

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        OrderedPairDouble startLoc = null;  
        double initialBearing = 0;
//    	if ((TimeLimitTextField.getText()).isEmpty()) {
//            StatusLabel.setText("Starting Default Mapping Routine ...");
//        } else
        StatusLabel.setText("Starting " + TimeLimitTextField.getText() + " Second Mapping Routine...");
        startLoc = new OrderedPairDouble(WorldView.WORLD_SIZE*WorldView.RESOLUTION/2, WorldView.WORLD_SIZE*WorldView.RESOLUTION/2); // default is middle of map
    	
        switch(StartingPositionComboBox.getSelectedIndex()) { // read the combo box value
        case 0: // Bottom Left Corner, Facing North (pi/2)
        	startLoc = new OrderedPairDouble(WorldView.WORLD_SIZE*WorldView.RESOLUTION/5, WorldView.WORLD_SIZE*WorldView.RESOLUTION/5);
        	initialBearing = Math.PI/2;        	
        	break;
        
        case 1: // Bottom Right Corner, Facing West (pi)
        	startLoc = new OrderedPairDouble(WorldView.WORLD_SIZE*WorldView.RESOLUTION*4/5, WorldView.WORLD_SIZE*WorldView.RESOLUTION/5);
        	initialBearing = Math.PI;        	
        	break;
        
        case 2: // Upper Left Corner, Facing East (0)
        	startLoc = new OrderedPairDouble(WorldView.WORLD_SIZE*WorldView.RESOLUTION/5, WorldView.WORLD_SIZE*WorldView.RESOLUTION*4/5);
        	initialBearing = 0;        	
        	break;
        
        case 3: // Upper Right Corner, Facing South (-pi/2) 
        	startLoc = new OrderedPairDouble(WorldView.WORLD_SIZE*WorldView.RESOLUTION*4/5, WorldView.WORLD_SIZE*WorldView.RESOLUTION*4/5);
        	initialBearing = -Math.PI/2;        	
        	break;
        	
        default:
        	startLoc = new OrderedPairDouble(WorldView.WORLD_SIZE*WorldView.RESOLUTION/5, WorldView.WORLD_SIZE*WorldView.RESOLUTION/5);
        	initialBearing = Math.PI/2;
        	System.out.println("Error: Invalid Combo Box Selection. \n... Reverting to Bottom Left Corner Initialization."); 
        	break;
        }
        
        StartGUI.started = true;
        ppt = new PathPlannerThread(Integer.parseInt((TimeLimitTextField.getText())), startLoc, initialBearing);
        ppt.start();
    }                                           

    @SuppressWarnings("deprecation")
	private void StopMotionActionPerformed(java.awt.event.ActionEvent evt) {                                           
            
        // stop motors, end path planner, proceed directly to map generation
    	if (StartGUI.started) {
    		LocationTracker.motors.setSpeed(0, 0); //immediately stop all motion
    	
	        if (PathPlannerThread.isRunning()) {
	    		StartGUI.ppt.stop(); // end PathPlannerThread (yes, i know this is deprecated)
	    		System.out.println("Killed Path Planner Thread.");
	        }
	        
	        StatusLabel.setText("Motion Stopped. \nYou may now close the window.");
    	} else {
    		StatusLabel.setText("Error: Path Planner has not been initialized or started.");
    	}
	}   
    

    private void StartingPositionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                         
    	// do nothing here
    }                                                        

    
    @SuppressWarnings("deprecation")
	private void EmergencyStopButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        
        // TODO maybe bring up a dialog box here?
        
    	if (StartGUI.started) {
    		LocationTracker.motors.setSpeed(0, 0); //immediately stop all motion
    	
	        if (PathPlannerThread.isRunning()) {
	    		StartGUI.ppt.stop(); // end PathPlannerThread (yes, i know this is deprecated)
	    		System.out.println("Killed Path Planner Thread.");
	        }
	        
	        System.out.println("Execution halted. System exiting.");
	        System.exit(0);
	        
    	} else {
    		StatusLabel.setText("Error: Path Planner has not been initialized or started.");
    	}
    	
        
    }                                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
        
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton EmergencyStopButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JComboBox StartingPositionComboBox;
    private javax.swing.JLabel StartingPositionLabel;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JButton StopMotion;
    private javax.swing.JLabel TimeLimitLabel;
    private javax.swing.JTextField TimeLimitTextField;
    // End of variables declaration
}
