package pharoslabut.radioMeter.cc2420;

/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../RadioSignalMeter.h.
 */

public class Constants  {
    public static final short TIMER_PERIOD_MILLI = 1024;
}
